### ISSUE TITLE
Parse binary-linking output from npm for nonstandard-binary-names

### ISSUE THREAD

**Issue by zkat** [zkat/npx#10]
Some npm packages don't export their primary binary under the same name as the package itself. In these cases, we should assume that if a package only defines a single binary, and you do `npm <pkg>` without a `-p` option, `<command>` will be translated to the actual command.

For example: `npx grunt-cli` instead of `npx -p grunt-cli grunt`.

For packages with multiple binaries, where none of the binaries have the same name as the package, this should not be done at all, and a `-p` option should be _required_.

The best way to do this would be to read npm's own output and parse out the binaries linked from there. This is kinda tricky right now 'cause the output just looks like `/Users/usr/.npm/_npx/bin/standard -> /Users/usr/.npm/_npx/lib/node_modules/foo/bin/cmd.js` and can be mixed in with arbitrary other output.

Instead, we'll need to patch npm so its `--json` output for `npm i` includes the linked binaries somewhere. We'll also have to output our own summary report in this case, in order to simulate the usual human output.

**Comment by tamzinblake** [comment]
Possibly helpful another example: `npx -p ember-cli ember`

**Comment by thomblake** [comment]
I wonder how often the package.json has a relevant entry, and how standard it is. Notice in ember-cli https://github.com/ember-cli/ember-cli/blob/master/package.json - there is a 'bin' listing all the bins.

**Comment by zkat** [comment]
@thomblake The tricky thing about this is that "which binary wins" when there's a conflict depends on the order the installation was done in, so I do need npm's own output to figure out which actual binary got installed (to do it right).

**Comment by tamzinblake** [comment]
I think I see - so right now if you `npx foo` than that means `npx -p foo foo` and we don't ever accidentally run `npx -p bar foo`, but we want to enable `npx grunt-cli` to mean `npx -p grunt-cli grunt` in cases where it's obvious that the thing to do is run `grunt`.  But then if you also have a package `foo` locally installed that exports a bin called `grunt-cli` then we're going to accidentally run that instead?

**Comment by zkat** [comment]
@thomblake depending on their install order, yeah

**Comment by zkat** [comment]
But binary name conflicts are rare and far apart, at least.

**Comment by zkat** [comment]
`npx@8.0.0` is able to do `npx ember-cli` and such and have it work. Closing.
