### ISSUE TITLE
document "npx -p node@8 <command>"

### ISSUE THREAD

**Issue by gr2m** [zkat/npx#119]
Hello friendly humans,

`npx` allowed us to [drop node < 8 support for semantic-release](https://github.com/semantic-release/semantic-release/pull/414) which is 💯 

We use `npx -p node@8 npm run semantic-release` as a fallback. I’ve see @zkat tweeting about it a few times which is how I know about it, but it’s currently not documented in the README? Is this a bug or a feature? 

I’m happy to help out, I’d appreciate pointers on how/where to add docs for it :) 
`npx -p npm@3 npm -v` works too, I don’t know what other magic features are supported ✨

**Comment by zkat** [comment]
https://github.com/zkat/npx#examples seems like a good place to add it, tbh. :)

Keep in mind that `-p node@8` is not really a magical npx feature. It's just a cool example -- `-p` just specifies what package to install and puts it in the path, and it just so happens that https://npm.im/node exists!

I've also mentioned to @js-n in the past that I'd love to have a link to https://github.com/js-n/awesome-npx in the readme, but they were holding off for a bit.

**Comment by zkat** [comment]
@gr2m can I expect a PR from you for this? ;)

**Comment by gr2m** [comment]
yes yes, please give me some more time, I got it bookmarked, just traveled past 3 weeks and transitioned between jobs at the same time. If someone wants me to beat me on it, be my guest :)
