### ISSUE TITLE
`--shell-auto-fallback` says `Trying with npx...` when it should not

### ISSUE THREAD

**Issue by vjpr** [zkat/npx#124]
For security, when no `@version` is appended, npx will not install/run then package.

Therefore, it should not say `trying with npx`.

```
$ cowsay
cowsay not found. Trying with npx...
not found: cowsay
zsh: command not found: cowsay

$ cowsay@1
cowsay@1 not found. Trying with npx...
# INSTALLS + RUNS...
```

**Comment by vjpr** [comment]
Ah wait, so it will try to use `npx --no-install` if no `@` sign present, which will:

1. run it if it is in `prefix/node_modules/.bin`
2. or fallback to `PATH`
3. or print `not found: cowsay`

```
  if ! [[ $1 =~ @ ]]; then
    npx --no-install "$@"
  else
    npx "$@"
  fi
```

So to be clear, maybe instead of just `not found: cowsay`, it could say that it was `not found (in PATH or $prefix/node_modules/.bin): cowsay`...if thats not too verbose.

---

Here are some `not found` cases. Clarifying the output could help people understand what is happening more easily.

```
$ npx --no-install fooooooo
not found: fooooooo
```

```
$ npx fooooooo
npm ERR! code E404
npm ERR! 404 Not Found: fooooooo@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Vaughan/.npm/_logs/2017-10-17T15_33_33_864Z-debug.log
Install for fooooooo@latest failed with code 1
```

```
$ fooooooo
fooooooo not found. Trying with npx...
not found: fooooooo
zsh: command not found: fooooooo
```

```
$ foooooo@latest
foooooo@latest not found. Trying with npx...
npx: installed 1 in 2.491s
command not found: foooooo
zsh: command not found: foooooo@latest
```

```
$ foooooooooooo@latest
foooooooooooo@latest not found. Trying with npx...
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for foooooooooooo

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Vaughan/.npm/_logs/2017-10-17T15_36_40_419Z-debug.log
Install for foooooooooooo@latest failed with code 1
```

**Comment by zkat** [comment]
Yes, it gets a bit confusing because the fallback defaults to `--no-install` (for security reasons). It is, in fact, trying things with npx, but the semantics are slightly different so it can surprise people.

idk what the best way to resolve this for users would be.

**Comment by zkat** [comment]
(oops, clicked wrong button).

**Comment by zkat** [comment]
on further thought -- no, this is actually working exactly as expected. Keep in mind that npx does more than just installing packages. It also prepends paths. Therefore, `Trying with npx...` means it's going to try and include your current project's `node_modules/.bin` to `PATH` before trying again.
