### ISSUE TITLE
`--quiet` argument doesn't suppress path to downloaded module

### ISSUE THREAD

**Issue by noelleleigh** [zkat/npx#131]
### Platform
- Windows 10 x64 (1709)
- PowerShell 5.1
- Node.js 8.9.1
- npm 5.5.1
- npx 9.7.1

### Issue
The `--quiet` option is supposed to "Suppress output from npx itself", but on Windows, the path to where npx downloads the module is still printed out even with that option included.

### Steps
```
C:\Users\nleigh> node -v
v8.9.1
C:\Users\nleigh> npm -v
5.5.1
C:\Users\nleigh> npx -v
9.7.1
C:\Users\nleigh> npx -q cowsay hey
C:\Users\nleigh\AppData\Roaming\npm-cache\_npx\3616\node_modules\cowsay\cli.js
 _____
< hey >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

This does not occur in my WSL install:
```
nleigh@WIN10-TYCHO:/mnt/c/Users/nleigh$ npx -q cowsay hey
 _____
< hey >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by noelleleigh** [comment]
After investigating a bit, this log message comes from: 
https://github.com/zkat/npx/blob/f64ae43ee64b1c5ad82cdb41c954f73e28bfdaee/index.js#L354

Since by default, running on Linux doesn't log that path (even without `--quiet`), would it make sense to just remove that last `.then()` call?

**Comment by noelleleigh** [comment]
@zkat Is the logging of the module path on Windows intended or not? If differing behavior from Linux is desired, than I can update that log call appropriately to respect `--quiet`. Otherwise, I'll just delete it.

**Comment by zkat** [comment]
I.... I have no idea why this would be doing `console.log`. That just seems very strange for this tool, in general. I bet it was just a debugging thing that stuck around. I'd totally take a PR to delete this.

**Comment by noelleleigh** [comment]
@zkat Done. These lines appear to have been added in this [commit](https://github.com/zkat/npx/commit/255aeeb7fd5625c4d4f56b080dc510f5047d4ed9) back in July, probably as debugging.
