### ISSUE TITLE
Allow custom registry

### ISSUE THREAD

**Issue by frediana** [zkat/npx#133]
Hello,

I have an issue running npx command on a specific package hosted on a custom registry (not npmjs.org)

Context:
- I'm using a custom NPM module registry: Nexus, inside my project I have a .npmrc with the registry parameter filled.
- We have some scoped packages, let says @mycompany/tools
- The module @mycompany/tools contains some binaries, let says foo.sh

Problem:
- If I clean my node_module, and run the following command:
```npx -p @mycompany/tools foo```

I get a 404, and when I look at the logs I can see that the request is made to //registry.npmjs.org/ not my local repository.

I cannot see any ```--registry``` option or so.

Proposition:
- I think the registry should be taken fron .npmrc if exists
- Do you think we could add a registry option to allow custom registry?

If I can help developping a solution, with some little guidance and aprovals I would be happy to help

Regards,

Adrien

**Comment by greyepoxy** [comment]
Running into what I think is a very similar issue to frediana (although frediana if you are in the context of a module with an .npmrc file there is a `--userconfig` option to point at your local npmrc file https://github.com/zkat/npx#description)

In my company I want to run a script that works very similar to createReactApp but the project hosting the script lives on a private repository.

I would like to do something like
`npx -registry https://my.companies.private.registry/ @MyCompany/CreateNewProject`
from a global context (not in the context of an existing repo with an .npmrc file

today to do this I do
```
npm install -g @MyCompany/CreateNewProject --registry https://my.companies.private.registry/
CreateNewProject
```
but would prefer to not pollute the global namespace and also need to remember to update the global install before running the script again.

A work around is to set the global registry value but would prefer to not do that

**Comment by zkat** [comment]
Hm. That's valid. I see why this would be a pain.

The main thing I'm afraid of is polluting npx's config space with the [enormous number of options npm has available](https://docs.npmjs.com/misc/config#config-settings), specially since npx already invokes npm under the hood -- and thus, any options available through local `.npmrc` files would be available as well. I believe that the more options you have to type, as a user, the less valuable a tool like npm becomes: I would argue that having to type out an entire registry URL is already a waste of time compared to just plain installing the tool, if you have to do it over and over.

I'm still open to the idea of adding this, but I hope you'll humor me for a moment with a couple possible alternative solutions:

The first is to configure your nexus registry so that it applies to scoped packages under `@MyCompany`. So, what that would look like would be:
```bash
$ echo "@mycompany:registry=https://my.companies.private.registry/" >> ~/.npmrc
$ npx @mycompany/create-new-project
-> it works! The command downloads this package from your private registry!
$ npx create-react-app
-> goes to registry.npmjs.com
```

I think this is probably the most convenient, if your `--registry` usage would be limited to scoped packages.

If not, then you can try the other alternative: using environment variables, that npm will then pick up. That would look like this:
```bash
$ npm_config_registry=https://my.companies.private.registry/ npx @mycompany/create-new-project
```

How do these solutions sound? Does the point I'm making about excessive configuration for a tool like npx make sense? Since it's meant to be _terse_?

**Comment by frediana** [comment]
Thank you for your response.

I wasn't aware we could configure registry so that it applies to scoped package but I think this solution will totally fit my needs.

I will soon put it in place, thanks for your help.

Adrien

**Comment by dominykas** [comment]
Defining the registry in `.npmrc` is something that works, but it still leaves you with having to type out the full package name for a command - it would be nice to be able to configure "shortcuts" for scoped/long name packages, e.g. an `.npxrc`:
```
[commands]
some-command=@mycompany/prefix-some-command
```
(This is a real life situation - we do have a `prefix` for our modules per, let's say, "project")

Having the above `.npxrc` you would no longer need to type out the full `npx -p @mycompany/prefix-some-command some-command`, but instead `npx some-command` would look it up automagically.

I'm happy to PR this, if we can agree on the config/scope/syntax.

**Comment by Den-dp** [comment]
I guess just because `node` comes with `npm` and `npx`, user's initial assumption will be "`npx` should use the same repository settings as `npm` will".

So it would be great if `npx` will be able to catch up at least repository from `.npmrc`.

**Comment by soundstep** [comment]
I was looking at npx to run scripts remotely from our jenkins jobs, from a private npm module.
But I just found out that I can't. It would be a great functionality though.
Would there be any problem using what's described in the `.npmrc` file?

Mine looks like this:
```
registry=http://domain.jfrog.io/repos/api/npm/npm-cie
_auth=TOKEN
always-auth=true
email=EMAIL
loglevel=warn
@jfrog:registry=http://domain.jfrog.io/repos/api/npm/npm-private
```

**Comment by zkat** [comment]
@soundstep @Den-dp if you read the thread, I explicitly mention that `.npmrc` is supported. If it's not working, please put together a repro and file a bug. It _should_ be picking it up.

@dominykas I will never add an `.npxrc`. In any way, shape or form. It adds too much complication for something that's supposed to be a straightforward tool, and it will kill a lot of its performance by forcing many fs checks where there are none. I'm just not interested, and configuring npm's behavior through the (SUPPORTED) `.npmrc` should be sufficient to cover that end of it.

**Comment by dominykas** [comment]
@zkat does `.npmrc` allow `[section]`s? Can you suggest a config for "command aliases", to avoid having to type the lengthy package names?

**Comment by zkat** [comment]
@dominykas if you're trying to save typing, I suggest you use standard shell aliases.

**Comment by soundstep** [comment]
Sorry @zkat I misunderstood and misled by an unrelated auth issue, my bad. It does indeed work, and it is great!

**Comment by zkat** [comment]
I'm going to close this. I don't see a compelling reason to have a `--registry` option available _on top of_ npm's own configuration. npm should be configured through `.npmrc` or through env vars that npm can read. Since it seems like registry stuff with npx is working as expected (by using whichever registry npm itself uses), I'm just gonna close this.

**Comment by vengal4327** [comment]
@soundstep How did you resolve your issue.. looks like It's not honoring npmrc config in my scenario too and I was wondering If I'm missing anything?

**Comment by soundstep** [comment]
@vengal4327 I had an auth issue, npx command works well with the `.npmrc` setup.

**Comment by vengal4327** [comment]
@soundstep I see in your case you have scope defined like @jfrog:registry=http://domain.jfrog.io/repos/api/npm/npm-private, But do you think It'll work if I just have registry=http://npm-private-location. In my case it's not pulling if it's defined in that way.

**Comment by ccarse** [comment]
I'd like to ask you to reconsider this. In my company each group runs their own registries but I'm building a tool that I plan on recommending to have users run with npx (so they don't run outdated versions they've globally installed) and for many users the only time they'll access this registry is when running this tool. So I'd much rather just have them copy/paste a command from the readme to run this tool which includes the registry than having to change their configuration. I hope that makes sense. Thank you, I love npx.

**Comment by mzyil** [comment]
@ccarse how about `npm_config_registry=http://localhost:4873 npx <command>`? this seems to work for me.

What is your OS? If it's Windows instead there is an equivalent cmd for that as well (setting env var inline)

**Comment by sinedied** [comment]
@mzyil it's not cross-platform.

@zkat 
> I'm going to close this. I don't see a compelling reason to have a --registry option available on top of npm's own configuration. npm should be configured through .npmrc or through env vars that npm can read. Since it seems like registry stuff with npx is working as expected (by using whichever registry npm itself uses), I'm just gonna close this.

npm supports configuring the registry either by using a .npmrc file or via the `--registry` param, so it should makes sense that npx supports the same flags (passing it to npm directly). It's especially useful if you have different registry environments, like in my case distinct nexus registries for dev/preprod/prod, and changing it through `.npmrc` does not make much sens in this case.

**Comment by mzyil** [comment]
@sinedied it's not hard to do in windows: https://www.google.com/search?q=windows+set+env+var+before+command

However ability to pass command line flags to npm should be available. Something like this:
`npx some-awesome-package -- --registry http://myspecialregisty.com`

The part after `--` is passed to npm

**Comment by sinedied** [comment]
@mzyil Not hard to do on windows, still no cross-platform solution to share 1-liner to everyone to quickly run command whatever is their environment.

And flags after `--` are not passed to npm, but to the target package command, so it's not working.
