### ISSUE TITLE
Unhelpful error message on Windows when package has no binaries

### ISSUE THREAD

**Issue by noelleleigh** [zkat/npx#137]
### Versions
**OS:** Windows 10 Pro x64
**Node:** v9.2.0
**npm:** 5.6.0
**npx:** 9.7.1

### Issue
On Windows, when using `npx` on a npm package that doesn't have any binaries for `npx` to run, the error message that is printed is unhelpful because it does not come from the appropriate context.

### Example
*(Using a minimal package: [0](https://www.npmjs.com/package/0))*

On Windows 10 (PowerShell):
```
C:\Users\nleigh\dev\npm-test> npx 0
npx: installed 1 in 1.952s
The "path" argument must be of type string
```

Comparison on WSL (bash):
```
nleigh@WIN10-TYCHO:/mnt/c/Users/nleigh/dev/npm-test$ npx 0
npx: installed 1 in 1.513s
command not found: 0
```
On Linux, the error message is appropriate and useful.

### Analysis
After digging around, I found where the behavior in Linux and Windows diverges.

https://github.com/zkat/npx/blob/357e6abc49077d7e4325406852d182220816e4f2/index.js#L85

On Linux, [`fs.readdir()`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) is called with "/home/[username]/.npm/_npx/[PID]/bin" as the path, but that "bin" directory doesn't exist if no binaries are included in the package, so that function throws an "ENOENT" error, which is caught by the `.then()`'s rejection handling, creating the "command not found" message.

On Windows, `fs.readdir()` is called with "C:\Users\[username]\AppData\Roaming\npm-cache\_npx\[PID]", which *does* exist, so the function doesn't throw any errors. Next, `npx` strips the "etc" and "node_modules" directories from the `bins` array, leaving it empty if no binaries are included in the package.
After some more operations, [`path.resolve()`](https://nodejs.org/api/path.html#path_path_resolve_paths) is called with the second argument being `undefined` due to the empty `bins` array, which is what leads to the *The "path" argument must be of type string* error that is caught by the next level of error handling and printed out to the user.

### Fix
After the "etc" and "node_modules" directories are removed from the `bins` array, add this conditional exception throw, copied from the one that is called on Linux:

```javascript
if (bins.length < 1) {
  throw new Error(Y()`command not found: ${argv.command}`)
}
```
Shall I put together a PR with this change and a regression test?

**Comment by noelleleigh** [comment]
@zkat Can I get some feedback on this issue and proposed fix?

**Comment by denishowe** [comment]
"Command not found" would be better than 'The "path" argument must be of type string' but wouldn't something like `npx can't run package FOO because ...` be even better?

**Comment by ericblade** [comment]
npx nyc --reporter=lcov mocha

works, but also reports "The 'path' argument must be of type string d:\src\node_modules\nyc\bin\nyc.js"
