### ISSUE TITLE
Sepulkas?

### ISSUE THREAD

**Issue by Spown** [zkat/npx#147]
How about a short explanation about what this package does? I came from [NPM: How to Prevent Permissions Errors](https://docs.npmjs.com/getting-started/fixing-npm-permissions) which just says "use npx" and your readme only explains _how_ things are done, but not _what are_ these things. What is this package used for exactly.

Thank you.

**Comment by katemihalikova** [comment]
There's a link to a [great article about `npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) at the bottom of the article you've linked to. Is that what you are looking for?

**Comment by Spown** [comment]
> npx is a tool intended to help round out the experience of using packages from the npm registry ... npx makes it easy to use CLI tools and other executables hosted on the registry

I would be very helpful to have in the head of your README.

**Comment by zkat** [comment]
@Spown you wanna PR that? :)

**Comment by Spown** [comment]
not really - I've switched to yarn and all associated problems went away...
