### ISSUE TITLE
Puzzling output: "npx: installed 1 in 1.419s"

### ISSUE THREAD

**Issue by denishowe** [zkat/npx#148]
Whenever I run npx it always says it "installed 1", even when I'm just asking it for help:

> C:\>npx -h
> npx: installed 1 in 1.419s
> The "path" argument must be of type string
> Execute binaries from npm packages.
> ...

Installed 1 what?  Why?

The next message it outputs 'The "path" argument must be of type string' is also completely spurious as I understand it.

It would be great to get rid of this confusing output or say what's really going on.

Windows 7 command prompt, node: v9.4.0, npx: 9.7.1.

Cheers

**Comment by laggingreflex** [comment]
Recently started using npx and was wondering the same thing. 

Is it because it might be installing (or trying to install) dependencies even though they're already installed? If that's the case I would like to disable this. (I know it's a feature of npx to download/install dependencies on the fly, but I don't need it and I'm worried it would cause delay where internet speed/ping isn't ideal.)

Edit: never mind, there's already `--no-install` switch. 

Edit2: However `npx -h --no-install` still outputs "installed 1 in xxx" message

**Comment by laggingreflex** [comment]
It seems to be installing a "prefix" package. It runs (in [npm/bin/npx.cmd]) `CALL "%NODE_EXE%" "%NPX_CLI_JS%" prefix -g` which is ≈ `node npx.js prefix -g` so npx tries to install [prefix](http://npmjs.com/prefix). 

Not sure why. Is `prefix` a command in Mac/*nix?

Edit: I think command is meant to be [`npm prefix`](https://docs.npmjs.com/cli/prefix) 

[npm/bin/npx.cmd]: https://github.com/npm/npm/blob/latest/bin/npx.cmd#L12

**Comment by styfle** [comment]
This sounds like a duplicate of #144

**Comment by denishowe** [comment]
@styfle You're right.

**Comment by artulito** [comment]
I found that this issue can be fixed by rearranging your path:
Put your npm folder before the node installation folder. Example:

C:\Users\Arif\AppData\Roaming\npm;C:\Program Files\nodejs\

**Comment by hendrics** [comment]
@artulito where did you do this? which env/windows variable? is it different for GitBash vs command line vs power shell?

**Comment by artulito** [comment]
@hendrics on the system env variables editor, to access it quickly, type 'env' in your start menu. 

This will work globally. 

Also, I think this issue is fixed already. Just upgrade to the latest node version.

**Comment by Neutrino-Sunset** [comment]
Rearranging the path didn't fix it for me.

**Comment by silkfire** [comment]
@zkat Any update on this? The paths are in different categories, NPM is bound to my user, whereas NodeJS is bound to the machine, so the order is not relevant in this case (I assume local runs before global anyway).

**Comment by benpolinsky** [comment]
@artulito Upgrading does not fix the problem.

**Comment by Darkle** [comment]
@zkat @artulito What does typing `where npx` in the terminal give you?
This is my output:
```
$ where npx
C:\Users\Coop\AppData\Roaming\npm\npx
C:\Users\Coop\AppData\Roaming\npm\npx.cmd
C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd

```

**Comment by DomDumont** [comment]
Rearranging the path DID fix it for me. Thanks

**Comment by artulito** [comment]
@Darkle This is mine

```
λ node --version                          
v10.5.0 

λ npx --version                           
6.1.0                                                
                                          
λ npm --version                           
6.1.0                                     
                                          
λ where npm                               
C:\Users\Arif\AppData\Roaming\npm\npm     
C:\Users\Arif\AppData\Roaming\npm\npm.cmd 
C:\Program Files\nodejs\npm               
C:\Program Files\nodejs\npm.cmd   

λ where npx                               
C:\Users\Arif\AppData\Roaming\npm\npx     
C:\Users\Arif\AppData\Roaming\npm\npx.cmd 
C:\Program Files\nodejs\npx               
C:\Program Files\nodejs\npx.cmd           
```

**Comment by artulito** [comment]
@silkfire the order is absolutely relevant. In windows, the global/system paths runs before the local/user paths. In which case, by rearranging the paths, I'm using my local version of npm & npx, which fixed this issue for me.

**Comment by jamessouth** [comment]
rearranging my PATH per @artulito and restarting fixed this for me.

**Comment by jbsulli** [comment]
I'm using NVM for Windows so I had to rearrange  `%NVM_HOME%` and `%NVM_SYMLINK%` so that `%NVM_HOME%` was after `%NVM_SYMLINK%`. I am not sure if this messes up NVM but it seems to have fixed `npx` 😛
