### ISSUE TITLE
What does this do

### ISSUE THREAD

**Issue by nikolas** [zkat/npx#149]
what the hel

**Comment by steamhammer** [comment]
There's detailed description in readme section. https://github.com/zkat/npx#description 
Have you tried to investigate it prior opening the ticket?

**Comment by gaearon** [comment]
This is a known troll, don’t bother engaging 😄 
https://github.com/facebookincubator/create-react-app/issues/3780

**Comment by steamhammer** [comment]
Oh, I see. Thanks for heads up. %)

**Comment by zkat** [comment]
I guess it's a troll
