### ISSUE TITLE
some puzzle about the param

### ISSUE THREAD

**Issue by baixiaoji** [zkat/npx#150]
Before today, when I run the command 
```bash
npx -p cowsay --help
```
it gave me the help content about the cowsay.

Today,when I run the same thing in the dash, it show me the the content about the npx.

![image](https://user-images.githubusercontent.com/21168366/34925750-3bc561c4-f9e6-11e7-9c3e-9018bf99c947.png)

but when I remove the param `-p` , show me the right thing.
more confuse about i  run the example the param `p` is work.
```
npx -p lolcatjs -p cowsay -c \
  'echo "$npm_package_name@$npm_package_version" | cowsay | lolcatjs'
``` 
![image](https://user-images.githubusercontent.com/21168366/34925822-c3b711ea-f9e6-11e7-8078-ed5da4a5bb63.png)

------
node: v6.9.1
npm: 5.6.0 
npx: 9.7.1

**Comment by zkat** [comment]
When you use `-p`, you need to repeat the binary name.

So: `npx cowsay` is the same as `npx -p cowsay cowsay`.

`npx -p cowsay --help` is the same as `npx --help`, because there's no command name, and so npx just uses `--help`.
