### ISSUE TITLE
Fail to run npx with --node-arg on Windows

### ISSUE THREAD

**Issue by generalov** [zkat/npx#170]
```
npx -v
10.0.1
```

I've tried to pass `--inspect ` command line argument to `node` interpreter:
```
npx -n --inspect eslint
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
Long argument version `npx --node-arg --inspect eslint` leads to the same error. However it runs perfectly without --node-arg: `npx eslint`.

**Comment by noelleleigh** [comment]
Submitted #173 to fix this
