### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by zkat** [zkat/npx#26]
The surface area is pretty minor for things that need to be translated: options, descriptions, and a couple of error messages. It should be pretty straightforward using https://npm.im/y18n 👍

**Comment by gorhgorh** [comment]
hi there I just finished the [french version](https://github.com/gorhgorh/npx) and i have seen this, in the ES version [here](https://github.com/zkat/npx/blob/latest/locales/es.json#L13) you have a %s interpolation that is NOT in the english [one](https://github.com/zkat/npx/blob/latest/locales/en.json#L13) , it should be there, isn't it ? (I can add that to the french pr, if it is needed)

Also, i could not find how to change the locale (this computer is set to en-uk) Is there a way to switch for testing

**Comment by zkat** [comment]
@gorhgorh you should be able to do `LC_ALL=fr node . --help` to test it out.

I think the interpolation you pointed out is deffo a bug in the english one. I'll fix that. And thank you!

**Comment by gorhgorh** [comment]
cool I learnt two tricks, thanks (didn't knew about the ```node .``` launching the main)

I'm finishing reviewing the trad in place, and send the PR

**Comment by zkat** [comment]
We've got some pretty nice i18n coverage so far, so I'm gonna close this. New languages always welcome!
