### ISSUE TITLE
i18n: update locale files for more translations!

### ISSUE THREAD

**Issue by zkat** [zkat/npx#39]
Hey y'all! `npx@6.0.0` added several new strings! Most of them are single-word translations so the usage examples actually have their names shown in the right language.

I already did all the languages I felt semi-confident in being able to at least butcher. I'd really appreciate it if y'all helped with the others! https://github.com/zkat/npx/commit/779d950f20abeecde90a0d74c9fed4bae34a85dc is the commit that added the strings, and you can just copy-paste that and fill the rest in. LMK if you have any questions!

### Needs updating

* [x] Catalan - `ca.json`
* [x] German - `de.json` (/cc @janl)
* [x] English - `en.json`
* [x] Spanish - `es.json`
* [x] French - `fr.json` (/cc @gorhgorh)
* [x] Japanese - `ja.json` (note: I butchered this badly. Please feel free to correct it!)
* [ ] Pirate - `pirate.json` (/cc @bnb @CodeTheory) (note: currently in #36)
* [x] Portuguese (BR) - `pt_BR.json` (/cc @cyberglot)
* [x] Romanian - `ro.json` (/cc @hisk)
* [x] Russian - `ru.json` (/cc @sobolevn)
* [x] Chinese (Simplified) - `zh_CN.json` (/cc @int64ago)

**Comment by zkat** [comment]
@simonua hey! I pinged jan about this before, but the `de` is missing some of the newer strings that need some new translations (check `en.json`). Can I interested you in picking that up? <3

**Comment by simonua** [comment]
@zkat, You bet! I'll take a look. One item I'm not clear about is what you mean by _manual page_ in this line:

> For the full documentation, see the manual page...

If you can point me in the right direction, I can pick the correct translation because whatever value is in the German locale now is not correct in any regard. I just don't quite know yet what to replace it with. =P

**Comment by zkat** [comment]
This is pretty much all set for now. Thanks everyone for the help!

![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-315499911_2-s4-v1.png?transparent=1&palette=1&width=246)
