### ISSUE TITLE
--loglevel -s

### ISSUE THREAD

**Issue by stevenvachon** [zkat/npx#47]
Will `--loglevel=silent` or `-s` be passed to `npm`?

There're others: https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties

**Comment by zkat** [comment]
@stevenvachon to suppress output from npm-related operations, use `-q`/`--quiet`. That will also omit the progress bar. You will still need to pass any silencing-related options to the subcommand if you want that command to be quiet.

As far as other options go: I am intentionally keeping the options that npx itself passes down to the CLI to a bare minimum. The only two that will be passed to npm are `--userconfig` and `--cache`. `-q` is its own separate mechanism. If you want any other npm-related configuration, you'll need to either use a project-local `.npmrc`, or use the `--userconfig` option directly.
