### ISSUE TITLE
npx'ing a scoped package does not work

### ISSUE THREAD

**Issue by coderbyheart** [zkat/npx#67]
```shell
% npx @coderbyheart/xkcd-password  
npx: installed 19 in 2.583s
command not found: xkcd-password
npx @coderbyheart/xkcd-password  4.93s user 0.35s system 189% cpu 2.794 total
```

The sourcecode for the package is here: https://github.com/coderbyheart/xkcd-password

The package is published as a scoped package at https://www.npmjs.com/package/@coderbyheart/xkcd-password

It seems npx ignores the scope when executing it.

Running npx from within the package source folder works:

```bash
~/git/xkcd-password (git)-[master] % npx @coderbyheart/xkcd-password                                                                                       :(
kerosine brunts shroffs aborally
```

**Comment by zkat** [comment]
@coderbyheart this is intentional: npx is meant to execute _binaries_, not execute arbitrary packages' `main`.

Just add `"bin": "./index.js"` and I think that'll work just fine 👍

**Comment by coderbyheart** [comment]
Duh, my bad!
Works now as expected.
Thanks!

**Comment by hon2a** [comment]
@coderbyheart Could you, please, go into detail of how this now works as expected? I ran into the very same problem just now and adding `bin` did _not_ solve my problem. Then I tried running `npx @coderbyheart/xkcd-password` and got the same error (`command not found`).

**Comment by coderbyheart** [comment]
Hm. Is your setup up to date? It works for me:
```
m@nanshe ~ % npx @coderbyheart/xkcd-password
npx: installed 19 in 1.686s
cheaply lucency kinsman stagey
```

**Comment by hon2a** [comment]
@coderbyheart Thanks for the info, must be my `npm` version then.

**Comment by coderbyheart** [comment]
Actually this could fix it for you: https://github.com/coderbyheart/xkcd-password/commit/f68e88123e5168e3b59e4d6ba34157399d89ad93

**Comment by hon2a** [comment]
@coderbyheart Or I might not have flagged my executable properly at all, we'll never know :) Thanks for the tip!
