### ISSUE TITLE
npx can't find npm on Win32

### ISSUE THREAD

**Issue by anaisbetts** [zkat/npx#8]
npx blows up with ENOENT on Win32 because it uses `spawn` directly with `npm` and on Win32, `spawn` doesn't run down `PATH`. I wrote code to fix this in the `spawn-rx` package but I wasn't sure if you wanted to take a dependency on it or just want to copy-paste the code:

https://github.com/paulcbetts/spawn-rx/blob/master/src/index.ts#L91

Let me know and I'll send in a PR

**Comment by zkat** [comment]
@paulcbetts `which` is already used in npx. I'll take a PR that does `return which('npm').then(npmPath => spawn(npmPath, ...))`, though, since I think that's the most sensible one. I'm pretty sure node-which pays attention to `$PATH`.

**Comment by zkat** [comment]
nm I'm touching the code right now so I'll do it myself :)

**Comment by zkat** [comment]
I've pushed this. It'll be included in the next release.

**Comment by zkat** [comment]
This is in `npx@2.0.0`
