### ISSUE TITLE
Manpage

### ISSUE THREAD

**Issue by strugee** [zkat/npx#81]
npx could use a manpage, just like npm.

Thanks for maintaining all this stuff <3

**Comment by zkat** [comment]
It has a manpage: `man npx` works already. Did it not work for you?

**Comment by zkat** [comment]
To be clear: https://github.com/zkat/npx/blob/latest/bin/package.template.json#L6 is where it gets included. And the build script generates the manpage from `README.md` at release time. I think very early versions of 9.0 failed to include the manpage, but the latest versions should definitely have it?

**Comment by strugee** [comment]
Weird. Doing `npm install -g npm@latest` again fixed it. Might've been a weird nvm thing?

**Comment by zkat** [comment]
maybe! idk

**Comment by strugee** [comment]
¯\_(ツ)_/¯
